/*
 * generated by Xtext 2.30.0
 */
package verification.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VerificationUiModule extends AbstractVerificationUiModule {

	public VerificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
