/*
 * generated by Xtext 2.30.0
 */
package verification;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VerificationStandaloneSetup extends VerificationStandaloneSetupGenerated {

	public static void doSetup() {
		new VerificationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
