/**
 * generated by Xtext 2.30.0
 */
package verification.verification.impl;

import org.eclipse.emf.ecore.EClass;

import verification.verification.Global;
import verification.verification.VerificationPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Global</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GlobalImpl extends VariableImpl implements Global
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GlobalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VerificationPackage.Literals.GLOBAL;
  }

} //GlobalImpl
