/**
 * generated by Xtext 2.30.0
 */
package verification.verification.impl;

import org.eclipse.emf.ecore.EClass;

import verification.verification.Local;
import verification.verification.VerificationPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Local</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LocalImpl extends VariableImpl implements Local
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VerificationPackage.Literals.LOCAL;
  }

} //LocalImpl
