/**
 * generated by Xtext 2.30.0
 */
package verification.verification.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import verification.verification.Alter;
import verification.verification.Automaton;
import verification.verification.Event;
import verification.verification.Global;
import verification.verification.Model;
import verification.verification.State;
import verification.verification.VerificationPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link verification.verification.impl.ModelImpl#getName <em>Name</em>}</li>
 *   <li>{@link verification.verification.impl.ModelImpl#getGlobals <em>Globals</em>}</li>
 *   <li>{@link verification.verification.impl.ModelImpl#getEvents <em>Events</em>}</li>
 *   <li>{@link verification.verification.impl.ModelImpl#getStates <em>States</em>}</li>
 *   <li>{@link verification.verification.impl.ModelImpl#getAlters <em>Alters</em>}</li>
 *   <li>{@link verification.verification.impl.ModelImpl#getAutomaton <em>Automaton</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getGlobals() <em>Globals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGlobals()
   * @generated
   * @ordered
   */
  protected EList<Global> globals;

  /**
   * The cached value of the '{@link #getEvents() <em>Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvents()
   * @generated
   * @ordered
   */
  protected EList<Event> events;

  /**
   * The cached value of the '{@link #getStates() <em>States</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStates()
   * @generated
   * @ordered
   */
  protected EList<State> states;

  /**
   * The cached value of the '{@link #getAlters() <em>Alters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlters()
   * @generated
   * @ordered
   */
  protected EList<Alter> alters;

  /**
   * The cached value of the '{@link #getAutomaton() <em>Automaton</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAutomaton()
   * @generated
   * @ordered
   */
  protected EList<Automaton> automaton;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VerificationPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VerificationPackage.MODEL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Global> getGlobals()
  {
    if (globals == null)
    {
      globals = new EObjectContainmentEList<Global>(Global.class, this, VerificationPackage.MODEL__GLOBALS);
    }
    return globals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Event> getEvents()
  {
    if (events == null)
    {
      events = new EObjectContainmentEList<Event>(Event.class, this, VerificationPackage.MODEL__EVENTS);
    }
    return events;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<State> getStates()
  {
    if (states == null)
    {
      states = new EObjectContainmentEList<State>(State.class, this, VerificationPackage.MODEL__STATES);
    }
    return states;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Alter> getAlters()
  {
    if (alters == null)
    {
      alters = new EObjectContainmentEList<Alter>(Alter.class, this, VerificationPackage.MODEL__ALTERS);
    }
    return alters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Automaton> getAutomaton()
  {
    if (automaton == null)
    {
      automaton = new EObjectContainmentEList<Automaton>(Automaton.class, this, VerificationPackage.MODEL__AUTOMATON);
    }
    return automaton;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VerificationPackage.MODEL__GLOBALS:
        return ((InternalEList<?>)getGlobals()).basicRemove(otherEnd, msgs);
      case VerificationPackage.MODEL__EVENTS:
        return ((InternalEList<?>)getEvents()).basicRemove(otherEnd, msgs);
      case VerificationPackage.MODEL__STATES:
        return ((InternalEList<?>)getStates()).basicRemove(otherEnd, msgs);
      case VerificationPackage.MODEL__ALTERS:
        return ((InternalEList<?>)getAlters()).basicRemove(otherEnd, msgs);
      case VerificationPackage.MODEL__AUTOMATON:
        return ((InternalEList<?>)getAutomaton()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VerificationPackage.MODEL__NAME:
        return getName();
      case VerificationPackage.MODEL__GLOBALS:
        return getGlobals();
      case VerificationPackage.MODEL__EVENTS:
        return getEvents();
      case VerificationPackage.MODEL__STATES:
        return getStates();
      case VerificationPackage.MODEL__ALTERS:
        return getAlters();
      case VerificationPackage.MODEL__AUTOMATON:
        return getAutomaton();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VerificationPackage.MODEL__NAME:
        setName((String)newValue);
        return;
      case VerificationPackage.MODEL__GLOBALS:
        getGlobals().clear();
        getGlobals().addAll((Collection<? extends Global>)newValue);
        return;
      case VerificationPackage.MODEL__EVENTS:
        getEvents().clear();
        getEvents().addAll((Collection<? extends Event>)newValue);
        return;
      case VerificationPackage.MODEL__STATES:
        getStates().clear();
        getStates().addAll((Collection<? extends State>)newValue);
        return;
      case VerificationPackage.MODEL__ALTERS:
        getAlters().clear();
        getAlters().addAll((Collection<? extends Alter>)newValue);
        return;
      case VerificationPackage.MODEL__AUTOMATON:
        getAutomaton().clear();
        getAutomaton().addAll((Collection<? extends Automaton>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VerificationPackage.MODEL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case VerificationPackage.MODEL__GLOBALS:
        getGlobals().clear();
        return;
      case VerificationPackage.MODEL__EVENTS:
        getEvents().clear();
        return;
      case VerificationPackage.MODEL__STATES:
        getStates().clear();
        return;
      case VerificationPackage.MODEL__ALTERS:
        getAlters().clear();
        return;
      case VerificationPackage.MODEL__AUTOMATON:
        getAutomaton().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VerificationPackage.MODEL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case VerificationPackage.MODEL__GLOBALS:
        return globals != null && !globals.isEmpty();
      case VerificationPackage.MODEL__EVENTS:
        return events != null && !events.isEmpty();
      case VerificationPackage.MODEL__STATES:
        return states != null && !states.isEmpty();
      case VerificationPackage.MODEL__ALTERS:
        return alters != null && !alters.isEmpty();
      case VerificationPackage.MODEL__AUTOMATON:
        return automaton != null && !automaton.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ModelImpl
