/**
 * generated by Xtext 2.30.0
 */
package verification.verification;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link verification.verification.Assignment#getCurrentVar <em>Current Var</em>}</li>
 *   <li>{@link verification.verification.Assignment#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see verification.verification.VerificationPackage#getAssignment()
 * @model
 * @generated
 */
public interface Assignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Current Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current Var</em>' containment reference.
   * @see #setCurrentVar(VariableReference)
   * @see verification.verification.VerificationPackage#getAssignment_CurrentVar()
   * @model containment="true"
   * @generated
   */
  VariableReference getCurrentVar();

  /**
   * Sets the value of the '{@link verification.verification.Assignment#getCurrentVar <em>Current Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current Var</em>' containment reference.
   * @see #getCurrentVar()
   * @generated
   */
  void setCurrentVar(VariableReference value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see verification.verification.VerificationPackage#getAssignment_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link verification.verification.Assignment#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Assignment
