/**
 * generated by Xtext 2.30.0
 */
package verification.verification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Automaton</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link verification.verification.Automaton#getName <em>Name</em>}</li>
 *   <li>{@link verification.verification.Automaton#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see verification.verification.VerificationPackage#getAutomaton()
 * @model
 * @generated
 */
public interface Automaton extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see verification.verification.VerificationPackage#getAutomaton_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link verification.verification.Automaton#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Location</b></em>' containment reference list.
   * The list contents are of type {@link verification.verification.Location}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' containment reference list.
   * @see verification.verification.VerificationPackage#getAutomaton_Location()
   * @model containment="true"
   * @generated
   */
  EList<Location> getLocation();

} // Automaton
