/**
 * generated by Xtext 2.30.0
 */
package verification.verification;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see verification.verification.VerificationPackage#getLocal()
 * @model
 * @generated
 */
public interface Local extends Variable
{
} // Local
