/**
 * generated by Xtext 2.30.0
 */
package verification.verification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link verification.verification.Model#getName <em>Name</em>}</li>
 *   <li>{@link verification.verification.Model#getGlobals <em>Globals</em>}</li>
 *   <li>{@link verification.verification.Model#getEvents <em>Events</em>}</li>
 *   <li>{@link verification.verification.Model#getStates <em>States</em>}</li>
 *   <li>{@link verification.verification.Model#getAlters <em>Alters</em>}</li>
 *   <li>{@link verification.verification.Model#getAutomaton <em>Automaton</em>}</li>
 * </ul>
 *
 * @see verification.verification.VerificationPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see verification.verification.VerificationPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link verification.verification.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Globals</b></em>' containment reference list.
   * The list contents are of type {@link verification.verification.Global}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Globals</em>' containment reference list.
   * @see verification.verification.VerificationPackage#getModel_Globals()
   * @model containment="true"
   * @generated
   */
  EList<Global> getGlobals();

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link verification.verification.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see verification.verification.VerificationPackage#getModel_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link verification.verification.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see verification.verification.VerificationPackage#getModel_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Alters</b></em>' containment reference list.
   * The list contents are of type {@link verification.verification.Alter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alters</em>' containment reference list.
   * @see verification.verification.VerificationPackage#getModel_Alters()
   * @model containment="true"
   * @generated
   */
  EList<Alter> getAlters();

  /**
   * Returns the value of the '<em><b>Automaton</b></em>' containment reference list.
   * The list contents are of type {@link verification.verification.Automaton}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Automaton</em>' containment reference list.
   * @see verification.verification.VerificationPackage#getModel_Automaton()
   * @model containment="true"
   * @generated
   */
  EList<Automaton> getAutomaton();

} // Model
