/*
 * generated by Xtext 2.30.0
 */
package verification.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import verification.ui.internal.VerificationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VerificationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VerificationActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VerificationActivator activator = VerificationActivator.getInstance();
		return activator != null ? activator.getInjector(VerificationActivator.VERIFICATION_VERIFICATION) : null;
	}

}
