/**
 * generated by Xtext 2.29.0
 */
package org.xtext.gsht.gSelfOperatingHeuristicText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init State</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.gsht.gSelfOperatingHeuristicText.GSelfOperatingHeuristicTextPackage#getInitState()
 * @model
 * @generated
 */
public interface InitState extends Initial
{
} // InitState
