/*
 * generated by Xtext 2.30.0
 */
package verification.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import verification.parser.antlr.internal.InternalVerificationParser;
import verification.services.VerificationGrammarAccess;

public class VerificationParser extends AbstractAntlrParser {

	@Inject
	private VerificationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVerificationParser createParser(XtextTokenStream stream) {
		return new InternalVerificationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public VerificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VerificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
