/*
 * generated by Xtext 2.30.0
 */
package verification.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import verification.ui.internal.VerificationActivator;

public class VerificationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VerificationActivator.getInstance().getInjector("verification.Verification");
	}

}
