/*
 * generated by Xtext 2.30.0
 */
package verification.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVerificationScopeProvider extends DelegatingScopeProvider {
}
