/*
 * generated by Xtext 2.29.0
 */
package org.xtext.gsht.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GSelfOperatingHeuristicTextUiModule extends AbstractGSelfOperatingHeuristicTextUiModule {

	public GSelfOperatingHeuristicTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
