/*
 * generated by Xtext 2.30.0
 */
package org.xtext.gsht.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGSelfOperatingHeuristicTextScopeProvider extends DelegatingScopeProvider {
}
